import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "../components/Providers";
import { Toaster } from 'react-hot-toast';
import { TanstackQueryProvider } from "@/components/provider/TanstackQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "STRK Events",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TanstackQueryProvider>
          <Providers>{children}</Providers>
          <Toaster position="bottom-left" />
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
